plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "spec/dummy/**/*"
    - "bin/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/integration/**/*"
    - "spec/unit/reap_table_spec.rb"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
